before_install: git fetch
language: java
jdk:
  - openjdk7
cache:
  directories:
  - "$HOME/.m2"
install: mvn -s .settings.xml install --batch-mode -DskipTests=true
script: mvn -s .settings.xml install

